shared: &shared
  app: %{app}
  token: 2def5bdfe89f8dda89d37fb95932483450cf995b20252fc60cbe82cf1e0688504a79c25bfcc52c123c9d37cc3b806753854b9b473e4f3ba8db415bbe40390fe6

development:
  <<: *shared
  host: localhost:3000

production:
  <<: *shared
  host: www.%{domain}

sandbox:
  <<: *shared
  host: www-sandbox.%{domain}

test:
  <<: *shared
  host: test.host
